parameters:
    tenant_class: Minotore\MultiTenancyBundle\Entity\Tenant

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Minotore\MultiTenancyBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Kernel.php}'

    